FROM python:3.11-slim

LABEL maintainer="reylife"

ARG APP_HOME=/app
WORKDIR ${APP_HOME}

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

ENTRYPOINT ["python"]
CMD ["app.py"]